[project]
name = "charcut"
version = "0.1.0"
description = "CharCut WebApp"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asgiref>=3.9.1",
    "flask>=3.1.1",
    "uvicorn>=0.35.0",
]
